//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExerciceWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etudiant
    {
        public int Id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<int> filiere_id { get; set; }
    
        public virtual Filiere Filiere { get; set; }
    }
}
